syscmdb/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView
from syscmdb.views import *

handler404 = page_not_found
handler500 = page_error

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/dashboard/')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^resources/', include('resources.urls')),
    url(r'^products/', include('products.urls')),
]

users/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'HeYang'
from django.conf.urls import url, include

from users import views
from users.user import views as user_views
from users.group import views as group_views
from users.perm import views as perm_views

urlpatterns = [
    url(r'^login/$', views.UserLoginView.as_view(), name='user_login'),
    url(r'^logout/$', views.UserLogoutView.as_view(), name='user_logout'),
    url(r'^user/', include([
        url(r'list/$', user_views.UserListView.as_view(), name='user_list'),
        url(r'set_perm/$', user_views.UserSetPermView.as_view(), name='user_set_perm'),
        url(r'create/$', user_views.UserCreateView.as_view(), name='user_create'),
        url(r'delete/$', user_views.UserDeleteView.as_view(), name='user_delete'),
        url(r'stop/$', user_views.UserStopView.as_view(), name='user_stop'),
        url(r'start/$', user_views.UserStartView.as_view(), name='user_start'),
        url(r'modify/$', user_views.UserModifyView.as_view(), name='user_modify'),
        url(r'set_password/$', user_views.UserSetPasswordView.as_view(), name='user_set_password'),
        url(r'modify_group/$', user_views.UserModifyGroupView.as_view(), name='user_modify_group'),
        url(r'detail/(?P<pk>[0-9]+)/$', user_views.UserDetailView.as_view(), name='user_detail'),
        url(r'create_password/$', user_views.UserConfigPasswordView.as_view(), name='user_create_password'),
        url(r'get_users/$', user_views.UserGetListView.as_view(), name='user_get_users'),
    ])),
    url(r'group/', include([
        url(r'list/$', group_views.GroupListView.as_view(), name='group_list'),
        url(r'create/$', group_views.GroupCreateView.as_view(), name='group_create'),
        url(r'delete/$', group_views.GroupDeleteView.as_view(), name='group_delete'),
        url(r'modify/$', group_views.GroupModifyView.as_view(), name='group_modify'),
        url(r'set_perm/$', group_views.GroupSetPermView.as_view(), name='group_set_perm'),
    ])),
    url(r'perm/', include([
        url(r'list/$', perm_views.PermListView.as_view(), name='perm_list'),
        url(r'create/$', perm_views.PermCreateView.as_view(), name='perm_create'),
        url(r'delete/$', perm_views.PermDeleteView.as_view(), name='perm_delete'),
    ])),
]

resources/models.py
from django.db import models
from products.models import Product


# Create your models here.


class Idc(models.Model):
    name = models.CharField(max_length=10, verbose_name='机房简称', unique=True)
    name_cn = models.CharField(max_length=32, verbose_name='机房中文名')
    address = models.CharField(max_length=64, null=True, blank=True, verbose_name='机房地址，云厂商可以不写')
    username = models.CharField(max_length=32, verbose_name='机房负责人')
    username_phone = models.CharField(max_length=32, verbose_name='机房负责人联系电话')
    phone = models.CharField(max_length=32, verbose_name='机房电话')
    email = models.EmailField(verbose_name='机房邮箱')

    class Meta:
        db_table = 'resources_idc'
        default_permissions = []
        permissions = (
            ('add_idc', '添加机房'),
            ('delete_idc', '删除机房'),
            ('view_idc', '查看机房'),
            ('modify_idc', '修改机房'),
        )


class ServerAuto(models.Model):
    ip_inner = models.CharField(max_length=32, verbose_name='连接IP地址', unique=True)
    port = models.IntegerField(verbose_name='连接端口')
    os_status_list = [
        (0, 'Linux'),
        (1, 'Windows'),
        (2, 'Mac')
    ]
    os_status = models.IntegerField(choices=os_status_list, verbose_name='操作系统')
    system_status_list = [
        (0, '虚拟机'),
        (1, '物理机')
    ]
    system_status = models.IntegerField(choices=system_status_list, verbose_name='机器类型')

    class Meta:
        default_permissions = []


class Server(models.Model):
    hostname = models.CharField(max_length=64, verbose_name='主机名')
    cpu_info = models.CharField(max_length=64, verbose_name='CPU型号')
    cpu_count = models.IntegerField(verbose_name='CPU物理个数')
    mem_info = models.CharField(max_length=32, verbose_name='内存信息')
    os_system = models.CharField(max_length=32, verbose_name='系统平台')
    os_system_num = models.IntegerField(verbose_name='系统平台位数')
    uuid = models.CharField(max_length=64, verbose_name='UUID')
    sn = models.CharField(max_length=64, verbose_name='SN')
    scan_status_list = [
        (0, '连接异常'),
        (1, '连接正常')
    ]
    scan_status = models.IntegerField(choices=scan_status_list, verbose_name='探测状态')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='创建主机时间')
    update_date = models.DateTimeField(auto_now=True, verbose_name='更新主机时间')
    server_auto = models.OneToOneField('ServerAuto')
    idcs = models.ForeignKey('Idc', null=True, on_delete=models.SET_NULL)
    product_one = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL, related_name='product_one',
                                    verbose_name='业务线')
    product_two = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL, related_name='product_two',
                                    verbose_name='二级业务线')
    product_host = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL, related_name='product_host',
                                     verbose_name='主机组')
    server_user = models.ForeignKey('ServerUser', null=True, on_delete=models.SET_NULL, verbose_name='管理用户')

    class Meta:
        default_permissions = []
        permissions = (
            ('view_server', '查看资产主机'),
            ('add_server', '添加资产主机'),
            ('delete_server', '删除资产主机'),
            ('server_set_product', '设置资产主机业务线'),
            ('server_scan_status', '资产主机刷新探测'),
        )


class Disk(models.Model):
    name = models.CharField(max_length=32, verbose_name='硬盘名')
    size = models.CharField(max_length=32, verbose_name='硬盘大小')
    server = models.ForeignKey(Server)

    class Meta:
        default_permissions = []


class Ip(models.Model):
    name = models.CharField(max_length=32, verbose_name='网卡名')
    ip_address = models.CharField(max_length=32, verbose_name='IP地址')
    server = models.ForeignKey(Server)

    class Meta:
        default_permissions = []


class ServerUser(models.Model):
    name = models.CharField(max_length=32, verbose_name='名称')
    username = models.CharField(max_length=32, verbose_name='系统用户')
    password = models.CharField(max_length=64, verbose_name='系统密码')
    info = models.TextField(verbose_name='备注')

    class Meta:
        default_permissions = []
        permissions = (
            ('add_serveruser', '添加资产用户'),
            ('delete_serveruser', '删除资产用户'),
            ('view_serveruser', '查看资产用户'),
            ('modify_serveruser', '修改资产用户'),
        )

resources/serveruser/views.py
# _*_ coding: utf-8 _*_
__author__ = 'HeYang'
from django.views.generic import TemplateView, ListView, DetailView, View
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from resources.models import ServerUser, Server


# 主机资源用户展示
class ServerUserListView(LoginRequiredMixin, ListView):
    template_name = 'serveruser/serveruser_list.html'
    model = ServerUser


# 主机资源用户创建
class ServerUserCreateView(LoginRequiredMixin, TemplateView):
    template_name = 'serveruser/serveruser_create.html'

    def get_context_data(self, **kwargs):
        context = super(ServerUserCreateView, self).get_context_data(**kwargs)
        context['server_list'] = Server.objects.filter(server_user=None)
        return context

    def post(self, request):
        ret = {'status': 0}
        try:
            server_user = ServerUser.objects.create(
                name=request.POST.get('name'),
                username=request.POST.get('username'),
                password=request.POST.get('password'),
                info=request.POST.get('info'),
            )
            serveruser_list = request.POST.getlist('serveruser_id')
            for server_id in serveruser_list:
                server = Server.objects.get(pk=server_id)
                server.server_user = server_user
                server.save()
            ret['msg'] = '创建成功'
        except Exception as e:
            print(e)
            ret['status'] = 1
            ret['msg'] = '创建失败'

        return JsonResponse(ret)


# 主机资源用户详情信息
class ServerUserDetailView(LoginRequiredMixin, DetailView):
    template_name = 'serveruser/serveruser_detail.html'
    model = ServerUser

    def get_context_data(self, **kwargs):
        context = super(ServerUserDetailView, self).get_context_data(**kwargs)
        context['server_list'] = Server.objects.all()
        return context


# 主机资源用户修改
class ServerUserModifyView(LoginRequiredMixin, View):

    def post(self, request):
        ret = {'status': 0}
        try:
            serveruser_id = request.POST.get('serveruser_id')
            password = request.POST.get('password')
            server_id_list = request.POST.getlist('server_id')
            if password:
                ServerUser.objects.filter(pk=serveruser_id).update(
                    name=request.POST.get('name'),
                    username=request.POST.get('username'),
                    password=password,
                    info=request.POST.get('info'),
                )
            else:
                ServerUser.objects.filter(pk=serveruser_id).update(
                    name=request.POST.get('name'),
                    username=request.POST.get('username'),
                    info=request.POST.get('info'),
                )
            serveruser = ServerUser.objects.get(pk=serveruser_id)
            serveruser.server_set.clear()
            for server_id in server_id_list:
                server = Server.objects.get(pk=server_id)
                server.server_user_id = serveruser_id
                server.save()
            ret['msg'] = '修改成功'
        except Exception:
            ret['status'] = 1
            ret['msg'] = '修改失败'
        return JsonResponse(ret)

resources/templates/serveruser/serveruser_create.html
{% extends 'public/layout.html' %}

{% block load_css %}
    <link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">

    <link href="/static/css/plugins/chosen/bootstrap-chosen.css" rel="stylesheet">

    <link href="/static/css/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet">

    <link href="/static/css/plugins/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet">

    <link href="/static/css/plugins/cropper/cropper.min.css" rel="stylesheet">

    <link href="/static/css/plugins/switchery/switchery.css" rel="stylesheet">

    <link href="/static/css/plugins/jasny/jasny-bootstrap.min.css" rel="stylesheet">

    <link href="/static/css/plugins/nouslider/jquery.nouislider.css" rel="stylesheet">

    <link href="/static/css/plugins/datapicker/datepicker3.css" rel="stylesheet">

    <link href="/static/css/plugins/ionRangeSlider/ion.rangeSlider.css" rel="stylesheet">
    <link href="/static/css/plugins/ionRangeSlider/ion.rangeSlider.skinFlat.css" rel="stylesheet">

    <link href="/static/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">

    <link href="/static/css/plugins/clockpicker/clockpicker.css" rel="stylesheet">

    <link href="/static/css/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet">

    <link href="/static/css/plugins/select2/select2.min.css" rel="stylesheet">

    <link href="/static/css/plugins/touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet">

    <link href="/static/css/plugins/dualListbox/bootstrap-duallistbox.min.css" rel="stylesheet">
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
{% endblock %}

{% block mbx %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-10">
            <h2></h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'index' %}">仪表盘</a>
                </li>

                <li>
                    <a>资产管理</a>
                </li>


                <li class="active">
                    <strong>创建资产用户</strong>
                </li>

            </ol>
        </div>
        <div class="col-sm-2">
        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>创建资产用户表单</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">


                        <form class="form-horizontal" enctype="multipart/form-data" id="create_form">
                            {% csrf_token %}
                            <h3>资产用户</h3>
                            <div class="form-group"><label class="col-md-2 control-label">名称</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control" placeholder="名称" name="name">
                                </div>
                            </div>

                            <div class="form-group"><label class="col-md-2 control-label">用户名</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control" placeholder="用户名" name="username">
                                </div>
                            </div>

                            <div class="form-group"><label class="col-md-2 control-label">密码</label>
                                <div class="col-md-9">
                                    <input type="password" class="form-control" placeholder="密码" name="password">
                                </div>
                            </div>

                            <div class="form-group"><label class="col-md-2 control-label">资产列表</label>
                                <div class="col-md-9">
                                    <select data-placeholder="选择资产主机" class="chosen-select" multiple
                                            style="width:350px;" tabindex="4" name="serveruser_id" size="5">
                                        {% for server in server_list %}
                                            <option value="{{ server.id }}">{{ server.hostname }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div class="form-group"><label class="col-md-2 control-label">备注</label>
                                <div class="col-md-9">
                                    <textarea type="text" class="form-control" placeholder="备注" cols="40" rows="5"
                                              name="info"></textarea>
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button class="btn btn-white" type="reset">重置</button>
                                    <button class="btn btn-primary" type="submit">提交</button>
                                </div>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block load_js %}
    <!-- Chosen -->
    <script src="/static/js/plugins/chosen/chosen.jquery.js"></script>

    <!-- JSKnob -->
    <script src="/static/js/plugins/jsKnob/jquery.knob.js"></script>

    <!-- Input Mask-->
    <script src="/static/js/plugins/jasny/jasny-bootstrap.min.js"></script>

    <!-- Data picker -->
    <script src="/static/js/plugins/datapicker/bootstrap-datepicker.js"></script>

    <!-- NouSlider -->
    <script src="/static/js/plugins/nouslider/jquery.nouislider.min.js"></script>

    <!-- Switchery -->
    <script src="/static/js/plugins/switchery/switchery.js"></script>

    <!-- IonRangeSlider -->
    <script src="/static/js/plugins/ionRangeSlider/ion.rangeSlider.min.js"></script>

    <!-- iCheck -->
    <script src="/static/js/plugins/iCheck/icheck.min.js"></script>

    <!-- MENU -->
    <script src="/static/js/plugins/metisMenu/jquery.metisMenu.js"></script>

    <!-- Color picker -->
    <script src="/static/js/plugins/colorpicker/bootstrap-colorpicker.min.js"></script>

    <!-- Clock picker -->
    <script src="/static/js/plugins/clockpicker/clockpicker.js"></script>

    <!-- Image cropper -->
    <script src="/static/js/plugins/cropper/cropper.min.js"></script>

    <!-- Date range use moment.js same as full calendar plugin -->
    <script src="/static/js/plugins/fullcalendar/moment.min.js"></script>

    <!-- Date range picker -->
    <script src="/static/js/plugins/daterangepicker/daterangepicker.js"></script>

    <!-- Select2 -->
    <script src="/static/js/plugins/select2/select2.full.min.js"></script>

    <!-- TouchSpin -->
    <script src="/static/js/plugins/touchspin/jquery.bootstrap-touchspin.min.js"></script>

    <!-- Tags Input -->
    <script src="/static/js/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>

    <!-- Dual Listbox -->
    <script src="/static/js/plugins/dualListbox/jquery.bootstrap-duallistbox.js"></script>

    <script src="/static/js/plugins/validate/jquery.validate.js"></script>
    <script src="/static/js/plugins/validate/messages_zh.js"></script>
    <script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>

    <script>
        $('.chosen-select').chosen({width: "100%"});

        $(document).ready(function () {
            $("#create_form").validate({
                rules: {
                    name: {
                        required: true,
                        maxlength: 10
                    },
                    username: {
                        required: true,
                        maxlength: 32
                    },
                    password: {
                        required: true,
                        maxlength: 64
                    },
                    info: {
                        required: true
                    }
                }, submitHandler: function () {
                    str = $('#create_form').serialize();
                    $.post('{% url 'serveruser_create' %}', str, function (res) {
                        console.log(res);
                        if (res.status == 0) {
                            swal({
                                title: res.msg,
                                type: 'success',
                                confirmButtonText: "OK"
                            }, function () {
                                window.location.href = '{% url 'serveruser_list' %}';
                            });
                        } else {
                            swal({
                                title: res.msg,
                                type: 'error',
                                confirmButtonText: "知道了"
                            });
                        }
                    });
                }
            });
        });

    </script>
{% endblock %}

resources/templates/serveruser/serveruser_list.html
{% extends 'public/layout.html' %}
{% load serveruser_tag %}

{% block load_css %}
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
{% endblock %}

{% block mbx %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-10">
            <h2></h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{% url 'index' %}">仪表盘</a>
                </li>

                <li>
                    <a>资源管理</a>
                </li>


                <li class="active">
                    <strong>资产用户</strong>
                </li>

            </ol>
        </div>
        <div class="col-sm-2">
        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>资产用户列表</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        {% if perms.resources.add_serveruser %}
                            <a href="{% url 'serveruser_create' %}" class="btn btn-sm btn-primary"> 添加资产用户 </a>
                        {% endif %}
                        <table class="table table-striped table-bordered table-hover  dataTable no-footer">
                            <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">名称</th>
                                <th class="text-center">用户</th>
                                <th class="text-center">关联资产</th>
                                <th class="text-center">备注</th>
                                {% if perms.resources.modify_serveruser or perms.resources.delete_serveruser %}
                                    <th class="text-center">操作</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% for serveruser_obj in object_list %}
                                <tr>
                                    <td class="text-center">{{ forloop.counter }}</td>
                                    <td class="text-center">{{ serveruser_obj.name }}</td>
                                    <td class="text-center">{{ serveruser_obj.username }}</td>
                                    <td class="text-center">{{ serveruser_obj.server_set.all | serveruser_count }}</td>
                                    <td class="text-center">{{ serveruser_obj.info }}</td>
                                    {% if perms.resources.modify_serveruser or perms.resources.delete_serveruser %}
                                        <td class="text-center">
                                            {% if perms.resources.modify_serveruser %}
                                                <a class="btn btn-xs btn-info"
                                                   href="{% url 'serveruser_detail' serveruser_obj.id %}">编辑</a>
                                            {% endif %}
                                            {% if perms.resources.delete_serveruser %}
                                                <a class="btn btn-xs btn-danger" id="serveruser_delete"
                                                   onclick="">删除</a>
                                            {% endif %}
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                        <div class="row">
                            <center>
                                <div class="btn-group">
                                    <a class="btn btn-white" href="{% url 'idc_list' %}?page=1">首页</a>
                                    {% if page_obj.has_previous %}
                                        <a class="btn btn-white" type="button"
                                           href="?page={{ page_obj.previous_page_number }}">
                                            上一页
                                        </a>
                                    {% else %}
                                        <a class="btn btn-white" type="button" disabled="disabled">上一页</a>
                                    {% endif %}

                                    {% for page in page_range %}
                                        {% ifequal page page_obj.number %}
                                            <a class="btn btn-white active">{{ page }}</a>
                                        {% else %}
                                            <a href="?page={{ page }}" class="btn btn-white">{{ page }}</a>
                                        {% endifequal %}
                                    {% endfor %}

                                    {% if page_obj.has_next %}
                                        <a class="btn btn-white" type="button"
                                           href="?page={{ page_obj.next_page_number }}">
                                            下一页
                                        </a>
                                    {% else %}
                                        <a class="btn btn-white" type="button" disabled>下一页</a>
                                    {% endif %}
                                    <a class="btn btn-white"
                                       href="{% url 'idc_list' %}?page={{ paginator.num_pages }}">末页</a>
                                </div>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block load_js %}
    <script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>
    <script>

        function idc_delete(idc_id) {
            var data = {};
            data['idc_id'] = idc_id;
            data['csrfmiddlewaretoken'] = "{{ csrf_token }}";
            $.ajax({
                url: '{% url 'idc_delete' %}',
                type: 'post',
                data: data,
                success: function (res) {
                    if (res.status == 0) {
                        swal({
                            title: res.msg,
                            type: 'success',
                            confirmButtonText: "OK"
                        }, function () {
                            window.location.reload()
                        });
                    } else {
                        swal({
                            title: res.msg,
                            type: 'error',
                            confirmButtonText: "知道了"
                        });
                    }
                }
            })
        };
    </script>
{% endblock %}